on:
  push:
    tags:
      - 'publish*'

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    steps:
      - name: ‚ôªÔ∏è Check out code
        uses: actions/checkout@v4
      - name: üì¶ Publish Custom Node
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: {% raw %}${{ secrets.REGISTRY_ACCESS_TOKEN }}{% endraw %}